spring:
  config:
    import: file:.env[.properties]
  application:
    name: kitchen
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/los_pollos_hermanos
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
rabbitmq:
  host: ${RABBIT_HOST}
  port: 5672
  username: ${RABBIT_USERNAME}
  password: ${RABBIT_PASSWORD}
  exchange:
    name: los_pollos_hermanos
  queueFood:
    name: food_item
  routingFood:
    key: los_pollos_hermanos-food_item
  queueWorker:
    name: worker
  routingWorker:
    key: los_pollos_hermanos-worker
workforce:
  amount: 6
