spring:
  application:
    name: kitchen
  datasource:
      url: "jdbc:postgresql://localhost:5432/los_pollos_hermanos"
      username: "admin"
      password: "admin123"
  jpa:
      show-sql: true
      properties:
          dialect: "org.hibernate.dialect.PostgreSQLDialect"
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  exchange:
    name: los_pollos_hermanos
  queueFood:
    name: food_item
  routingFood:
    key: los_pollos_hermanos-food_item
  queueWorker:
    name: worker
  routingWorker:
    key: los_pollos_hermanos-worker
workforce:
  amount: 6